export {
  EARTH_RADIUS_METERS,
  assertBoundingBox,
  boundingBoxContains,
  haversineDistanceMeters,
  isValidCoordinate,
  resolveCoordinatePrecedence,
  verifyGeocodedCoordinate,
  verifyOrganizerCoordinate,
  type AcceptedCoordinatePrecision,
  type BoundingBox,
  type CoordinatePrecedenceDecision,
  type CoordinatePrecision,
  type CoordinateRejection,
  type CoordinateRejectionCode,
  type CoordinateSource,
  type CoordinateVerdict,
  type CoordinateVerificationOptions,
  type GeocodeCandidate,
  type OrganizerCoordinate,
  type VerifiedCoordinate,
} from "@porchfest/core";
